In [ ]:
import numpy as np
import hapke
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
from scipy import optimize
from mpl_toolkits import mplot3d
from scipy.interpolate import interp1d
from pyvims import VIMS
from pyvims.misc import MAPS
import random
from pyvims.misc import Map
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
import matplotlib.patches as patches
from matplotlib.patches import Polygon
from pathlib import Path
from pyvims.wget import wget
plt.rcParams.update({'font.size': 12})

Load cube (using hapke.retrieve_cube) and optical constants (hapke.opticalconstants)

In [ ]:
file_path = 'C:/Users/USUARIO/Desktop/MSc Thesis/Phase A - Data Analysis/Data/Rhea/R2.txt'
try:
    with open(file_path, 'r') as file:
        # Read the entire file content into a single string
        file_contents = file.read()

        # Split the string by spaces to create a list of values
        ids = file_contents.split()

except FileNotFoundError:
    print(f"The file '{file_path}' was not found.")
except Exception as e:
    print(f"An error occurred: {str(e)}")
cubes_R2 = {}
for id in ids:
    cubes_R2[id] = VIMS(id, root='C:/Users/USUARIO/Desktop/MSc Thesis/Phase A - Data Analysis/Data/Rhea/R4',download=False)
print(cubes_R2)

In [ ]:
is_pixel = []
pixel = []

for key in cubes_R2.keys():

    if cubes_R2[key].get_pixel(20,20) == None:
        is_pixel.append(False)
        pixel.append(None)
    else:
        is_pixel.append(True)
        pixel.append(cubes_R2[key].get_pixel(20,20))


In [ ]:
for p in range(len(pixel)):
    if is_pixel[p]:
        ax = hapke.plot_pixel_equi(2.03,cubes_R2[ids[p]],[(pixel[p].s,pixel[p].l)],background=False)


In [47]:
IF = {}
wav1 = {}
angles = {}

fits = {}
angles = {}

D_fit = []
error_D = []
theta_fit = []
legend = []

fig, ax = plt.subplots()
ax.set_xlabel(r'Wavelength [$\mu$m]')
ax.set_ylabel('I/F')
ax.set_title('')
ax.set_xlim(1.1,3.3)
ax.grid()

ini_par = [0.7,0.00001]

for p in range(len(pixel)):
    if is_pixel[p]:
        IF[ids[p]] = pixel[p].spectrum
        wav1[ids[p]] = pixel[p].wvlns

        angles[ids[p]] = [np.deg2rad(pixel[p].eme),np.deg2rad(pixel[p].inc),np.deg2rad(pixel[p].phase)]

        fits[ids[p]] = optimized_parameters = optimize.least_squares(hapke.cost_function_mixed, ini_par, args=(wav, angles[ids[p]], IF[ids[p]], wav1[ids[p]],n_c,k_c,n_a,k_a,0,2.8)
                                                                     )
        print(fits[ids[p]].x)

        ax.plot(wav1[ids[p]],IF[ids[p]])

        error_D.append(hapke.print_error_correlation(fits[ids[p]])[1])

        legend.append(ids[p])
        D_fit.append(fits[ids[p]].x[1])
        theta_fit.append(fits[ids[p]].x[0])



plt.show()


[1.50332919e+00 3.46502826e-06]
Parameter 1: 1.5033291948639003 +/- 0.028678
Parameter 2: 3.4650282559410565e-06 +/- 0.000005

Cost = 36.031151220612415

Correlation matrix:
[[ 1.         -0.74622334]
 [-0.74622334  1.        ]]
[7.08134520e-01 7.68180958e-05]
Parameter 1: 0.7081345195943879 +/- 0.106548
Parameter 2: 7.681809581952608e-05 +/- 0.000018

Cost = 2.4324897526730402

Correlation matrix:
[[ 1.         -0.64542637]
 [-0.64542637  1.        ]]
[6.95497763e-01 7.69126428e-05]
Parameter 1: 0.6954977628097244 +/- 0.109388
Parameter 2: 7.691264277472667e-05 +/- 0.000018

Cost = 2.472429567927128

Correlation matrix:
[[ 1.        -0.6460203]
 [-0.6460203  1.       ]]
[6.97241642e-01 7.75157416e-05]
Parameter 1: 0.6972416419242473 +/- 0.113672
Parameter 2: 7.751574155246294e-05 +/- 0.000019

Cost = 2.564209435636377

Correlation matrix:
[[ 1.         -0.65041439]
 [-0.65041439  1.        ]]
[9.73741410e-01 6.08123988e-05]
Parameter 1: 0.9737414097107752 +/- 0.069325
Parameter 2: 6.0

C:\Users\USUARIO\PycharmProjects\pythonProject\hapke.py:438: RuntimeWarning: invalid value encountered in log
  multipleScattering = (1 - w * x * (r_0 + ((1 - 2 * r_0 * x) / 2) * np.log((1 + x) / x))) ** (-1)


[1.52866332e+00 3.32076108e-06]
Parameter 1: 1.5286633191532566 +/- 0.012289
Parameter 2: 3.3207610758028665e-06 +/- 0.000004

Cost = 34.99370846725622

Correlation matrix:
[[ 1.         -0.68302847]
 [-0.68302847  1.        ]]
[6.98563448e-01 8.54890818e-05]
Parameter 1: 0.6985634484410228 +/- 0.123786
Parameter 2: 8.54890818184264e-05 +/- 0.000020

Cost = 2.477397574747878

Correlation matrix:
[[ 1.         -0.63487719]
 [-0.63487719  1.        ]]
[1.50572791e+00 6.56261309e-06]
Parameter 1: 1.505727912961114 +/- 0.018362
Parameter 2: 6.562613092636686e-06 +/- 0.000005

Cost = 31.507818645023352

Correlation matrix:
[[ 1.        -0.6865828]
 [-0.6865828  1.       ]]
[6.98916086e-01 8.46747914e-05]
Parameter 1: 0.6989160864926174 +/- 0.121857
Parameter 2: 8.46747914394527e-05 +/- 0.000020

Cost = 2.423628641040016

Correlation matrix:
[[ 1.         -0.63361827]
 [-0.63361827  1.        ]]
[1.49776204e+00 8.13596924e-06]
Parameter 1: 1.4977620445129143 +/- 0.019839
Parameter 2: 8.13596

KeyboardInterrupt: 

In [49]:
fig, (ax) = plt.subplots()

ax.errorbar(legend, np.array(D_fit)*1000000,yerr=np.array(error_D)*1000000, fmt='-o')
ax.set_ylabel(r'D')

ax.set_xlabel(r'Experiment')
ax.grid()
plt.legend()

plt.show()

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.


KeyboardInterrupt: 

In [ ]:
#cube_id = '1741560738_11'
#cube_id_2 = '1646250341_1'

#cube = hapke.retrieve_cube(cube_id)
#cube2 = hapke.retrieve_cube(cube_id_2)

T = 120
N = 20

opt_c = hapke.opticalconstants(T,sensitivity = N)
n_c = opt_c['n']
k_c = opt_c['k']
wav_c = opt_c['wav']

opt_a = hapke.opticalconstants(T, sensitivity= N,crystallinity=False)
n_a = opt_a['n']
k_a = opt_a['k']
wav_a = opt_a['wav']

int_opt = hapke.inter_optical_constants(wav_c, wav_a, n_c, k_c)

wav = np.array(int_opt['wav'])
n_c = int_opt['n']
k_c = int_opt['k']


In [ ]:
bg = MAPS[cube.target_name]
fig, ax = bg.figure(figsize=(20, 10))

ax.add_collection(cube.pixels(2.03, vmin=.05, vmax=.18))
plt.show()

In [ ]:
pixel = cube.get_pixel(25,8)

ax = hapke.plot_pixel_equi(2.03,cube,[(pixel.s,pixel.l)],background=True)

plt.show()

In [ ]:
pixel1 = cube@(13, 50)

e, i, phase = [np.deg2rad(pixel1.eme),np.deg2rad(pixel1.inc),np.deg2rad(pixel1.phase)]


angles = [e,i,phase]
IF1 = pixel1.spectrum
wav1 = pixel1.wvlns
ini_par = [0.1,0.00001]

body = 0

optimized_parameters = optimize.least_squares(
    hapke.cost_function_mixed, ini_par, args=(wav, angles, IF1, wav1,n_c,k_c,n_a,k_a,0,2.8)
)

optimized_values = optimized_parameters.x
hapke.print_error_correlation(optimized_parameters)

print('')

ini_mass = 0.1

cryst_fit = optimize.least_squares(
        hapke.cost_function_mixed_mass_fraction, ini_mass, args=(wav, angles, IF1, wav1,n_c,k_c,n_a,k_a,optimized_values,1.45,1.8,1.8), bounds=([0],[1]),
)

hapke.print_error_correlation(cryst_fit)

print('1.2-1.65 RATIO: ' + str(hapke.crystallinity_coecient(IF1,wav1)))

print('')
print('Longitude: ' + str(pixel1.lon))
print('Latitude: ' + str(pixel1.lat))
print('Phase: ' + str(pixel1.phase))

In [ ]:
print(hapke.cryst_area(IF1,wav1)['area'])
print(hapke.cryst_area(hapke.hapke_model_mixed(optimized_values, wav, angles, n_c, k_c, n_a, k_a)['IF'],wav)['area'])
print(hapke.cryst_area(IF1,wav1)['area']/hapke.cryst_area(hapke.hapke_model_mixed(optimized_values, wav, angles, n_c, k_c, n_a, k_a)['IF'],wav)['area'])

In [ ]:
fig, ax = plt.subplots()
ax.plot(wav1, IF1)
ax.plot(wav, hapke.hapke_model_mixed(optimized_values, wav, angles, n_c, k_c, n_a, k_a)['IF'], ls = ':')
ax.plot(wav, hapke.hapke_model_mixed_mass_fraction(cryst_fit.x, wav, angles, n_c, k_c, n_a, k_a,optimized_values)['IF'], ls = '-.')
ax.set_xlabel(r'Wavelength [$\mu$m]')
ax.set_ylabel('I/F')
ax.set_title('')
ax.set_xlim(1.1,3.3)
ax.grid()
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
#ax.legend()
plt.show()

In [ ]:
pixel1 = cube@(30,15)

e, i, phase = [np.deg2rad(pixel1.eme),np.deg2rad(pixel1.inc),np.deg2rad(pixel1.phase)]


angles = [e,i,phase]
IF1 = pixel1.spectrum
wav1 = pixel1.wvlns
ini_par = [0.1,np.deg2rad(20),0.1,0.00005,0.5]

body = cube.target_name

optimized_parameters = optimize.least_squares(
    hapke.cost_function_mixed_no_weight, ini_par, args=(wav, angles, IF1, wav1,n_c,k_c,n_a,k_a,1.5,1.85,body), bounds=([0.001,0,0,0,0], [1,np.deg2rad(44.9),0.74,0.001,1], ), x_scale='jac',
)

optimized_values = optimized_parameters.x
hapke.print_error_correlation(optimized_parameters)

print('')
print('Longitude: ' + str(pixel1.lon))
print('Latitude: ' + str(pixel1.lat))
print('Phase: ' + str(pixel1.phase))

This cell below created 20 randomly generated initial parameters and store the results of the fits on a dictionary fit_dict. The variable count adds one every time a set of generated initial parameters leads to the same solution than the previous one.

In [ ]:
fit_dict = {}
count = 0
n_fits = 20

for i in range(n_fits):
    param = [random.random()*0.74,random.random()*0.001,random.random()]
    optimized_parameters = optimize.least_squares(
        hapke.cost_function_mixed_no_weight, param, args=(wav, angles, IF1, wav1,n_c,k_c,n_a,k_a,0,2.8,body), bounds=([0.00001,0.000001,0], [0.74,0.001,1], ),
    )

    fit_dict[i] = {'x': optimized_parameters.x, 'cost': optimized_parameters.cost}

    if i == 0:

        opt_param =  optimized_parameters.x
        opt_cost = optimized_parameters.cost
        count += 1
        print(optimized_parameters.x)
        print('COST = ' + str(optimized_parameters.cost))

    elif i >= i:

        rel_er1 = abs(opt_param[0] - optimized_parameters.x[0]) / opt_param[0]
        rel_er2 = abs(opt_param[1] - optimized_parameters.x[1]) / opt_param[1]
        rel_er3 =abs(opt_param[2] - optimized_parameters.x[2]) / opt_param[2]

        if rel_er1 > 0.0001 or rel_er2 > 0.0001 or rel_er3 > 0.0001:
            print('PARAMETERS CHANGED')
            best_fit =  optimized_parameters
            print(optimized_parameters.x)
            print('COST = ' + str(optimized_parameters.cost))
        else:
            count += 1
print(count)

In [ ]:
fit_dict = {}
count = 0
n_fits = 20

for i in range(n_fits):
    param = [random.random(),random.random()*np.deg2rad(44.5),random.random()*0.74,random.random()*0.001,random.random()]
    optimized_parameters = optimize.least_squares(
        hapke.cost_function_mixed_no_weight, param, args=(wav, angles, IF1, wav1,n_c,k_c,n_a,k_a,0,2.8,body), bounds=([0.001,0,0,0,0], [1,np.deg2rad(44.9),0.74,0.001,1], ),
    )

    fit_dict[i] = {'x': optimized_parameters.x, 'cost': optimized_parameters.cost}

    if i == 0:

        opt_param =  optimized_parameters.x
        opt_cost = optimized_parameters.cost
        count += 1
        print(optimized_parameters.x)
        print('COST = ' + str(optimized_parameters.cost))

    elif i >= i:

        rel_er1 = abs(opt_param[0] - optimized_parameters.x[0]) / opt_param[0]
        rel_er2 = abs(opt_param[1] - optimized_parameters.x[1]) / opt_param[1]
        rel_er3 =abs(opt_param[2] - optimized_parameters.x[2]) / opt_param[2]
        rel_er4 = abs(opt_param[3] - optimized_parameters.x[3]) / opt_param[3]
        rel_er5 =abs(opt_param[4] - optimized_parameters.x[4]) / opt_param[4]

        if rel_er1 > 0.0001 or rel_er2 > 0.0001 or rel_er3 > 0.0001 or rel_er4 > 0.0001 or rel_er5 > 0.0001:
            print('PARAMETERS CHANGED')
            best_fit =  optimized_parameters
            print(optimized_parameters.x)
            print('COST = ' + str(optimized_parameters.cost))
        else:
            count += 1
print(count)

In [ ]:
print(fit_dict)

In [ ]:
optimized_values = optimized_parameters.x

old_hapke = hapke.hapke_model_mixed(ini_par,wav, angles, n_c,k_c,n_a,k_a,body)['IF']

new_hapke = hapke.hapke_model_mixed(optimized_values,wav, angles, n_c,k_c,n_a,k_a,body)['IF']

fig, ax = plt.subplots(figsize = (8,3))
ax.plot(wav, old_hapke, label = 'Hapke Initial')
ax.plot(wav, new_hapke, label = 'Hapke Optimized')
ax.plot(wav1, IF1, label = 'Pixel')
ax.set_xlabel('Wavelength [$\mu$m]')
ax.set_ylabel('I/F')
ax.set_xlim(1.1,3.2)
ax.set_title('')
ax.legend()
plt.show()

In [ ]:
plt.figure(figsize=(12, 8))

plt.imshow(cube@2.03, extent=cube.extent, cmap='gray', vmin=0, vmax=.18)

plt.colorbar(extend='max', label='I/F')

plt.scatter(13, 50, s=150)

plt.xlabel(cube.slabel)
plt.ylabel(cube.llabel)

plt.xticks(cube.sticks)
plt.yticks(cube.lticks)
plt.show()

These coming two cells plot the surface response: the residuals compared to the spectrum taken by VIMS. Note that wa1 and IF1 need to be defined beforehand and that the function hapke_mixed needs to be changes to be 2D in parameters

In [ ]:
# SURFACE RESPONSE OF ENCELADUS SPECTRA

real_par = [0.51,0.00007]

m_range = np.linspace(0.001,1,30)
phi_range = np.linspace(0.001,0.74,30)

residuals = np.zeros((len(phi_range),len(m_range)))


interp_func_2 = interp1d(wav1, IF1, bounds_error=False)

interpolated_lab = interp_func_2(wav)

for i in range(len(phi_range)):
    for j in range(len(m_range)):
        param = [phi_range[i], m_range[j]]
        dif = (interpolated_lab - hapke.hapke_model_mixed(param,wav,angles,n_c,k_c,n_a,k_a,body)['IF'])
        dif = dif[~np.isnan(dif)]
        residuals[i,j] = np.linalg.norm(dif)

In [ ]:
# 3D PLOT OF THE SURFACE RESPONSE

phi_range, m_range = np.meshgrid(phi_range, m_range)
# Define the data

# Create a 3D plot
fig = plt.figure(figsize = (4,4))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(phi_range, m_range, residuals.T, cmap='viridis')
ax.scatter(0.16933,0.502, c = 'green', label = 'Real solution' )
ax.legend()
ax.set_xlabel(r'$\phi$ [-]')
ax.set_ylabel(r'$m$ [-]')
ax.set_zlabel('Residuals')
# Show the plot
plt.show()